### ISSUE TITLE
Fix Conversion of Long Worlds

### ISSUE THREAD

**Issue by BJTMastermind** [BJTMastermind/Indev-To-Infdev-World-Converter#9] opened 2021-03-14 06:02 UTC
When Converting Long worlds they seem to be messed up. Might have to change for loop that converts the indev world to chunks and use the world size instead of a start position or a combination of both.

**Comment by VoxelBill** [comment] 2021-03-14 21:29
This issue seems to not be an issue with the for loop but something else. Will continue to look for the cause and fix this.

**Comment by VoxelBill** [comment] 2021-03-16 04:05
Added a check at the start of the program that won't allow the converter to work if the Width and Length of the world are not the same for now. This issue seems to be something that might require a redo of a lot of the code so I'm just not going to allow them to convert until I figure it out.

**Comment by VoxelBill** [comment] 2021-10-30 04:08
Long World Conversion has been fixed without major changes to any of the code and will be available in the next update.

**Closed as completed** 2021-11-11 03:38 UTC
Labels: bug, Indev
